In [1]:
import pandas as pd

In [2]:
businessFrame = pd.read_csv("business.csv", index_col=False)
reviewFrame = pd.read_csv("review.csv", index_col=False)

In [3]:
businessFrame = businessFrame[['categories', 'business_id']]
reviewFrame = reviewFrame[['text', 'business_id', 'useful']]

In [4]:
tag=["Food","Restaurants","Fast Food","Bars","Coffee & Tea"]

In [5]:
b_row = businessFrame.shape[0]

In [6]:
isFood = []
for i in range(0,b_row):
    isFood.append(any(t in tag for t in eval(businessFrame.iloc[:,0][i])))

In [7]:
df_food = businessFrame[isFood].copy()

In [8]:
b_row = df_food.shape[0]
print(b_row)

67882


In [9]:
df_food.index = range(b_row)

In [10]:
label_set = []
for i in range(0,b_row):
    for t in eval(df_food.iloc[:,0][i]):
        label_set.append(t)
label_set = label_set

In [11]:
import collections
freqdict=collections.Counter(label_set)

In [12]:
import numpy as np

In [13]:
def find_the_max(list1,diction):
    count=0
    item="CANCEL"
    for j in list1:
        if j!="Food" and j!="Restaurants" and j!="Nightlife":
            if diction[j]>count:
                count=diction[j]
                if j=="American (Traditional)" or j=="American (New)":
                    j="American"
                item=j
    return item

In [14]:
truelabel=[]
for i in range(b_row):
    truelabel.append(find_the_max(eval(df_food.iloc[:,0][i]),freqdict))

In [15]:
df_food["Truelabel"]=truelabel

In [16]:
df_food

categories  \
0      ['Food', 'Soul Food', 'Convenience Stores', 'R...   
1                               ['Food', 'Coffee & Tea']   
2                          ['Sandwiches', 'Restaurants']   
3      ['Flowers & Gifts', 'Bakeries', 'Grocery', 'Sh...   
4      ['Burgers', 'Bars', 'Restaurants', 'Sports Bar...   
5                             ['Chinese', 'Restaurants']   
6                   ['Food', 'Bakeries', 'Coffee & Tea']   
7      ['Sandwiches', 'Restaurants', 'Italian', 'Dine...   
8                       ['Chicken Wings', 'Restaurants']   
9                          ['Pubs', 'Nightlife', 'Bars']   
10     ['Restaurants', 'Seafood', 'American (Traditio...   
11                            ['Burgers', 'Restaurants']   
12     ['Comfort Food', 'Canadian (New)', 'Restaurant...   
13     ['Taiwanese', 'Food', 'Coffee & Tea', 'Restaur...   
14     ['Burgers', 'Chicken Wings', 'Bars', 'Restaura...   
15     ['Pubs', 'Restaurants', 'Bars', 'Irish', 'Nigh...   
16     ['Chicken Wings', 'Sandwiches', 'Restaurants',...   
17                                  ['Bakeries', 'Food']   
18                                   ['Food', 'Grocery']   
19                            ['Restaurants', 'Chinese']   
20                  ['Nightlife', 'Restaurants', 'Bars']   
21                 ['Bars', 'Pubs', 'Nightlife', 'Food']   
22         ['Asian Fusion', 'Restaurants', 'Sushi Bars']   
23     ['Restaurants', 'Specialty Food', 'French', 'B...   
24     ['American (Traditional)', 'Restaurants', 'Bar...   
25                            ['Restaurants', 'Mexican']   
26     ['Restaurants', 'American (Traditional)', 'Mex...   
27     ['Food', 'Shopping', 'Grocery', 'Delis', 'Gift...   
28                                    ['Food', 'Donuts']   
29     ['Nightlife', 'Lounges', 'Beer', 'Wine & Spiri...   
...                                                  ...   
67852  ['Food Court', 'Fast Food', 'Restaurants', 'Ko...   
67853     ['Restaurants', 'Soup', 'Sandwiches', 'Delis']   
67854            ['Restaurants', 'Fast Food', 'Burgers']   
67855                                ['Grocery', 'Food']   
67856              ['Food', 'Ice Cream & Frozen Yogurt']   
67857  ['Restaurants', 'Sandwiches', 'Coffee & Tea', ...   
67858              ['Ice Cream & Frozen Yogurt', 'Food']   
67859  ['Bars', 'Lounges', 'American (Traditional)', ...   
67860  ['Restaurants', 'Buffets', 'Salad', 'Soup', 'V...   
67861  ['Chicken Wings', 'Chinese', 'Seafood', 'Resta...   
67862       ['Italian', 'Restaurants', 'Canadian (New)']   
67863            ['Burgers', 'Restaurants', 'Fast Food']   
67864  ['Japanese', 'Barbeque', 'Restaurants', 'Korean']   
67865      ['Breakfast & Brunch', 'Restaurants', 'Food']   
67866  ['Food', 'Automotive', 'Convenience Stores', '...   
67867  ['Food', 'Ice Cream & Frozen Yogurt', 'Coffee ...   
67868                         ['Restaurants', 'Mexican']   
67869   ['Mexican', 'Tapas/Small Plates', 'Restaurants']   
67870  ['Gas Stations', 'Restaurants', 'Car Wash', 'D...   
67871  ['Restaurants', 'Chicken Wings', 'Fast Food', ...   
67872                       ['Restaurants', 'Argentine']   
67873                           ['Coffee & Tea', 'Food']   
67874                        ['Restaurants', 'Hot Dogs']   
67875                         ['Restaurants', 'Mexican']   
67876                           ['Pizza', 'Restaurants']   
67877  ['Restaurants', 'Delis', 'Sandwiches', 'Food S...   
67878  ['Food', 'Taiwanese', 'Restaurants', 'Coffee &...   
67879                         ['Restaurants', 'Burgers']   
67880                  ['American (New)', 'Restaurants']   
67881  ['Fashion', 'Shopping', 'Food', 'Department St...   

                     business_id                  Truelabel  
0      b'mLwM-h2YhXl2NCgdS84_Bw'         Convenience Stores  
1      b'v2WhjAB3PIBA8J8VxG3wEg'               Coffee & Tea  
2      b'duHFBe87uNSXImQmvBh87Q'                 Sandwiches  
3      b'n33Izvzk_z9_51H6NsQF-A'                    Grocery  
4      b'SDMRxm

In [17]:
def find_country(dataf,name):
    count=[]
    for k in range(dataf.shape[0]):
        count.append(dataf.iloc[k,2]==name)
    return count

In [19]:
aa= np.logical_or(find_country(df_food,"American"),find_country(df_food,"Chinese"))
bb=np.logical_or(find_country(df_food,"Italian"),find_country(df_food,"Japanese"))
cc=np.logical_or(find_country(df_food,"Mexican"),find_country(df_food,"Indian"))
dd=np.logical_or(find_country(df_food,"Thai"),find_country(df_food,"French"))
final1=np.logical_or(aa,bb)
final2=np.logical_or(cc,dd)
final=np.logical_or(final1,final2)

In [20]:
dffinal_food=df_food[final].copy()

In [21]:
dffinal_food.index = range(dffinal_food.shape[0])

In [23]:
finalnewdf=pd.merge(dffinal_food, reviewFrame, on='business_id').iloc[:,2:5].copy()

In [24]:
dfff=finalnewdf[finalnewdf.iloc[:,2]>1]

In [25]:
dfff.index = range(dfff.shape[0])

In [26]:
dfff

Truelabel                                               text  useful
0       American  b"Red Lobster!! My first experience with this ...       3
1       American  b'First and probably last time I dine at this ...       3
2        Chinese  b"We had dinner at Szechuan Cuisine on Easter ...       2
3        Chinese  b"I don't claim to be a Chinese Food aficionad...       2
4        Chinese  b"Tongue-numbingly good!  We got here 20 minut...       2
5        Mexican  b"I used to really like El Toro which was in t...       4
6        Mexican  b'I watched Undercover Boss one night and the ...       3
7        Italian  b"Visiting from Los Angeles, and to be honest,...       3
8        Italian  b'Food was ok, wasn\'t worth the high price. S...       3
9        Italian  b'Came here for dinner one night when hubby an...       6
10       Italian  b'I came to Bice for a wedding reception and f...       2
11       Italian  b"I thought I already found THE perfect italia...       3
12       Italian  b'wow what a place! The food is great, and no ...       2
13      American  b'My sister and I stopped in on a Sunday for b...       2
14       Chinese  b'Very good service , very good food. Used thi...       2
15       Chinese  b'Tried this little gem of a Chinese hotspot t...       2
16       Chinese  b"Okay. What a trip.\n\nSo, I copied and paste...       4
17       Chinese  b"All your essential Filipino needs in a littl...       2
18       Chinese  b'Not my first choice when it comes to asian m...       6
19       Chinese  b"Reading the prior reviews, they are pretty a...       4
20       Chinese  b"I've been going to this mini mart since they...       2
21       Chinese  b"Just got back and it's a nice little store. ...       2
22       Chinese  b"We come to this store often solely because i...       3
23       Mexican  b"Let's start at the wait. We were told 20 min...       3
24       Mexican  b"Aw I am sad to see so many negative reviews....       2
25       Mexican  b"Another night at Don Ruben's food outstandin...       2
26       Mexican  b'My mother, aunt and I went to this restauran...       4
27       Mexican  b"Totally underwhelming Mexican food.  Even Ma...       3
28       Mexican  b"I totally disagree with the one star review....       2
29       Mexican  b"Manager Stacy has much reflection to do. Ama...       2
...          ...                                                ...     ...
176929   Mexican  b'I skimmed some of the reviews - and whoah - ...       2
176930   Mexican  b"Fail...everything about this was just a fail...       2
176931   Mexican  b"Yay for blatant discrimination against famil...       3
176932   Mexican  b'After booking our trip to Toronto, I just kn...      17
176933   Mexican  b'Great Food, Awesome Atmosphere but terrible ...       2
176934   Mexican  b'Some restaurants are great for a date, El Ca...       2
176935   Mexican  b'I think this is one of the best looking rest...       3
176936   Mexican  b'I have been eating here for a long time ther...       3
176937   Mexican  b"I honestly don't know why anyone reviewed th...       2
176938   Mexican  b"This is a terrific family owner & operated r...       2
176939   Mexican  b'Good neighborhood spot.  Service is fast and...       2
176940   Mexican  b"Bottom line: Nino's is nothing special.  We ...       4
176941   Mexican  b'Store-bought corn chips, weak salsa, soggy b...       2
176942   Mexican  b'Great inexpensive Mexican food in the Sun Ci...       2
176943   Mexican  b'The Salsa Is Great, Ordered a Shredded Beef ...       2
176944   Mexican  b"As always, I love Nino's.  Last night my fri...       2
176945   Mexican  b'I\'ll start with the most positive statement...       4
176946   Mexican  b"We decided to try this place because of the ...       4
176947  American  b'I\'ve been to Quark\'s twice, most recently ...       2
176948  American  b"Really should be 2.5 stars. The service was ...       2
176949  American  b'After the Star Trek Experience, we 

In [28]:
labels = ["American", "Mexican", "Chinese", "Japanese", "Thai", "Italian", "Indian", "French"]
dfs = []
dft = []
for label in labels:
    kk=int(np.sum(dfff.iloc[:,0]==label)*0.8)
    dfs.append(dfff[dfff.iloc[:,0]==label][0:kk])
    dft.append(dfff[dfff.iloc[:,0]==label][kk:])
pdd=pd.concat(dfs)
pdt=pd.concat(dft)

In [29]:
pdd=pdd.sort_index().copy()
pdd.index = range(pdd.shape[0])

In [96]:
pdt=pdt.sort_index().copy()
pdt.index = range(pdt.shape[0])

In [32]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

Using TensorFlow backend.
/Users/zhanghaochong/anaconda/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [98]:
MAX_NB_WORDS = 4000
tokenizer = Tokenizer(num_words=MAX_NB_WORDS)

In [118]:
review_train = [string[1:].replace("\\n", "") for string in pdd["text"]]

In [119]:
review_test = [string[1:].replace("\\n", "") for string in pdt["text"]]

In [121]:
MAX_SEQUENCE_LENGTH = 200
fit_texts = review_train + review_test
tokenizer.fit_on_texts(fit_texts)
sequences = tokenizer.texts_to_sequences(review_train)
data_train = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
sequences = tokenizer.texts_to_sequences(review_test)
data_test = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)

In [169]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
# encode class values as integers
Y = pdd["Truelabel"]
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
y_train = np_utils.to_categorical(encoded_Y)

In [172]:
# encode class values as integers
Y = pdt["Truelabel"]
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
y_test = np_utils.to_categorical(encoded_Y)

In [124]:
x_train=data_train
x_test=data_test

In [86]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence

In [126]:
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(MAX_NB_WORDS, embedding_vecor_length, input_length=MAX_SEQUENCE_LENGTH))
model.add(LSTM(100))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['top_k_categorical_accuracy'])
print(model.summary())
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=3, batch_size=64)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_12 (Embedding)     (None, 200, 32)           128000    
_________________________________________________________________
lstm_12 (LSTM)               (None, 100)               53200     
_________________________________________________________________
dense_15 (Dense)             (None, 8)                 808       
_________________________________________________________________
dense_16 (Dense)             (None, 8)                 72        
Total params: 182,080
Trainable params: 182,080
Non-trainable params: 0
_________________________________________________________________
None
Train on 141563 samples, validate on 35396 samples
Epoch 1/3
141563/141563 [==============================] - 648s 5ms/step - loss: 0.2938 - top_k_categorical_accuracy: 0.9305 - val_loss: 0.2393 - val_top_k_categorical_accuracy: 0.9664
Epoch 2/3
141563/141563 [==

In [159]:
scores = model.evaluate(x_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 98.20%


In [173]:
labels = list(encoder.classes_)

In [190]:
sequences = tokenizer.texts_to_sequences([review_test[2000]])
test_x = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
y_predicted = model.predict(test_x)
zipped = zip(labels, y_predicted[0])
print(sorted(zipped, key=lambda elem: elem[1], reverse=True))

[('American', 0.94617993), ('Italian', 0.028832154), ('French', 0.016530983), ('Mexican', 0.0073498785), ('Japanese', 0.00088603923), ('Chinese', 0.00012618215), ('Indian', 8.6365435e-05), ('Thai', 8.5172587e-06)]


In [189]:
pdt["Truelabel"][2000]

'American'

In [192]:
review_self = "I like the rice bowl here! Kung pao chicken is fantastic"
sequences = tokenizer.texts_to_sequences([review_self])
test_x = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
y_predicted = model.predict(test_x)
zipped = zip(labels, y_predicted[0])
print(sorted(zipped, key=lambda elem: elem[1], reverse=True))

[('Chinese', 0.82682431), ('Mexican', 0.089538909), ('Japanese', 0.040690515), ('American', 0.034057643), ('Thai', 0.0046253861), ('Italian', 0.0036418522), ('Indian', 0.00034739164), ('French', 0.00027392083)]


In [117]:
from keras.preprocessing.text import Tokenizer
# define 5 documents
docs = ['Well done well!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!']
# create the tokenizer
t = Tokenizer(num_words=3)
# fit the tokenizer on the documents
t.fit_on_texts(docs)
sents = t.texts_to_sequences(docs)
# summarize what was learned
print(t.word_counts)
print(t.document_count)
print(t.word_index)
print(t.word_docs)
# integer encode documents
encoded_docs = t.texts_to_matrix(docs, mode='count')
print(encoded_docs)

OrderedDict([('well', 2), ('done', 1), ('good', 1), ('work', 2), ('great', 1), ('effort', 1), ('nice', 1), ('excellent', 1)])
5
{'well': 1, 'work': 2, 'done': 3, 'good': 4, 'great': 5, 'effort': 6, 'nice': 7, 'excellent': 8}
{'done': 1, 'well': 1, 'work': 2, 'good': 1, 'great': 1, 'effort': 1, 'nice': 1, 'excellent': 1}
[[ 0.  2.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


In [37]:
sents

[[1, 1], [2], [], [2], []]